import { Organization, Contact, OutreachActivity } from './types'

export const SEED_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-001',
    organization_name: 'Portland State University',
    target_category: 'university',
    organization_type_detail: 'Transportation Research & Education Center (TREC)',
    website: 'https://trec.pdx.edu',
    location_city: 'Portland',
    location_state: 'OR',
    region: 'Pacific Northwest',
    notes: 'TREC is one of the top transportation research centers. Strong pedestrian safety research including signal timing studies.',
    had_prior_ss4a_grant: 'no',
    has_action_plan: 'yes',
    action_plan_type: 'vision_zero',
    ss4a_stage: 'has_action_plan',
    underserved_community_relevance: 'high',
    pedestrian_safety_relevance: 'high',
    university_research_strength: 'high',
    grant_partner_fit: 'high',
    strategic_notes: 'TREC researchers have published on pedestrian signal timing. Natural fit for WalkPhase validation study.',
    source: 'Research',
    created_at: '2026-03-15T10:00:00Z',
    updated_at: '2026-03-28T14:00:00Z',
  },
  {
    id: 'org-002',
    organization_name: 'City of Orlando',
    target_category: 'city',
    organization_type_detail: 'Municipal Government — Transportation Department',
    website: 'https://www.orlando.gov/transportation',
    location_city: 'Orlando',
    location_state: 'FL',
    region: 'Southeast',
    notes: 'Orlando has one of the highest pedestrian fatality rates in the US. Active Vision Zero program.',
    had_prior_ss4a_grant: 'yes',
    has_action_plan: 'yes',
    action_plan_type: 'ss4a_action_plan',
    ss4a_stage: 'implementation_candidate',
    underserved_community_relevance: 'high',
    pedestrian_safety_relevance: 'high',
    university_research_strength: 'not_applicable',
    grant_partner_fit: 'high',
    strategic_notes: 'Prior SS4A Action Plan grantee. Could use WalkPhase data to support Implementation grant application.',
    source: 'SS4A Award List FY23',
    created_at: '2026-03-16T09:00:00Z',
    updated_at: '2026-03-29T11:00:00Z',
  },
  {
    id: 'org-003',
    organization_name: 'University of North Carolina Highway Safety Research Center',
    target_category: 'research_center',
    organization_type_detail: 'Pedestrian & Bicycle Safety Research',
    website: 'https://www.hsrc.unc.edu',
    location_city: 'Chapel Hill',
    location_state: 'NC',
    region: 'Southeast',
    notes: 'HSRC is a national leader in pedestrian and bicycle safety research. Runs the Pedestrian and Bicycle Information Center.',
    had_prior_ss4a_grant: 'no',
    has_action_plan: 'no',
    action_plan_type: 'unknown',
    ss4a_stage: 'likely_planning_candidate',
    underserved_community_relevance: 'medium',
    pedestrian_safety_relevance: 'high',
    university_research_strength: 'high',
    grant_partner_fit: 'high',
    strategic_notes: 'Could partner on research validation of WalkPhase methodology. PBIC connection valuable for credibility.',
    source: 'Research',
    created_at: '2026-03-17T08:00:00Z',
    updated_at: '2026-03-27T16:00:00Z',
  },
  {
    id: 'org-004',
    organization_name: 'MetroPlan Orlando',
    target_category: 'mpo',
    organization_type_detail: 'Metropolitan Planning Organization',
    website: 'https://metroplanorlando.org',
    location_city: 'Orlando',
    location_state: 'FL',
    region: 'Southeast',
    notes: 'MPO for the greater Orlando region. Coordinates transportation planning across Orange, Osceola, and Seminole counties.',
    had_prior_ss4a_grant: 'yes',
    has_action_plan: 'yes',
    action_plan_type: 'ss4a_action_plan',
    ss4a_stage: 'active_grantee',
    underserved_community_relevance: 'high',
    pedestrian_safety_relevance: 'high',
    university_research_strength: 'not_applicable',
    grant_partner_fit: 'medium',
    strategic_notes: 'Already an active grantee — may be harder to sell to, but could be a reference customer or pilot partner.',
    source: 'SS4A Award List FY24',
    created_at: '2026-03-18T10:00:00Z',
    updated_at: '2026-03-28T09:00:00Z',
  },
  {
    id: 'org-005',
    organization_name: 'City of Phoenix',
    target_category: 'city',
    organization_type_detail: 'Municipal Government — Street Transportation Department',
    website: 'https://www.phoenix.gov/streets',
    location_city: 'Phoenix',
    location_state: 'AZ',
    region: 'Southwest',
    notes: 'Phoenix has extreme heat conditions that affect pedestrian behavior and crossing speeds. High pedestrian fatality rate.',
    had_prior_ss4a_grant: 'no',
    has_action_plan: 'yes',
    action_plan_type: 'vision_zero',
    ss4a_stage: 'planning_demo_candidate',
    underserved_community_relevance: 'high',
    pedestrian_safety_relevance: 'high',
    university_research_strength: 'not_applicable',
    grant_partner_fit: 'high',
    strategic_notes: 'No prior SS4A grant + Vision Zero plan = ideal new entrant. Heat impacts on walking speed make WalkPhase especially relevant.',
    source: 'Research',
    created_at: '2026-03-19T11:00:00Z',
    updated_at: '2026-03-30T08:00:00Z',
  },
  {
    id: 'org-006',
    organization_name: 'Georgia Institute of Technology',
    target_category: 'university',
    organization_type_detail: 'School of Civil and Environmental Engineering',
    website: 'https://ce.gatech.edu',
    location_city: 'Atlanta',
    location_state: 'GA',
    region: 'Southeast',
    notes: 'Strong transportation engineering program. Research on adaptive signal control and pedestrian detection.',
    had_prior_ss4a_grant: 'no',
    has_action_plan: 'no',
    action_plan_type: 'unknown',
    ss4a_stage: 'likely_planning_candidate',
    underserved_community_relevance: 'medium',
    pedestrian_safety_relevance: 'high',
    university_research_strength: 'high',
    grant_partner_fit: 'high',
    strategic_notes: 'Georgia Tech could provide academic validation. Potential co-PI on a research-focused SS4A application.',
    source: 'Research',
    created_at: '2026-03-20T09:00:00Z',
    updated_at: '2026-03-29T10:00:00Z',
  },
  {
    id: 'org-007',
    organization_name: 'San Antonio–Bexar County MPO',
    target_category: 'mpo',
    organization_type_detail: 'Regional Metropolitan Planning Organization',
    website: 'https://www.sa-mpo.org',
    location_city: 'San Antonio',
    location_state: 'TX',
    region: 'South Central',
    notes: 'San Antonio has significant pedestrian safety challenges. Growing city with underserved communities.',
    had_prior_ss4a_grant: 'no',
    has_action_plan: 'no',
    action_plan_type: 'unknown',
    ss4a_stage: 'likely_planning_candidate',
    underserved_community_relevance: 'high',
    pedestrian_safety_relevance: 'high',
    university_research_strength: 'not_applicable',
    grant_partner_fit: 'medium',
    strategic_notes: 'No prior SS4A engagement — could be a strong new entrant. Large underserved population.',
    source: 'Research',
    created_at: '2026-03-21T08:00:00Z',
    updated_at: '2026-03-28T12:00:00Z',
  },
  {
    id: 'org-008',
    organization_name: 'City of Detroit',
    target_category: 'city',
    organization_type_detail: 'Municipal Government — Department of Public Works',
    website: 'https://detroitmi.gov',
    location_city: 'Detroit',
    location_state: 'MI',
    region: 'Midwest',
    notes: 'Detroit has significant pedestrian safety issues, particularly in underserved neighborhoods. Limited signal infrastructure in some areas.',
    had_prior_ss4a_grant: 'yes',
    has_action_plan: 'yes',
    action_plan_type: 'ss4a_action_plan',
    ss4a_stage: 'has_action_plan',
    underserved_community_relevance: 'high',
    pedestrian_safety_relevance: 'high',
    university_research_strength: 'not_applicable',
    grant_partner_fit: 'high',
    strategic_notes: 'Has SS4A Action Plan and strong equity narrative. Ready for implementation grant with WalkPhase data.',
    source: 'SS4A Award List FY22',
    created_at: '2026-03-22T10:00:00Z',
    updated_at: '2026-03-30T07:00:00Z',
  },
  {
    id: 'org-009',
    organization_name: 'Texas A&M Transportation Institute',
    target_category: 'research_center',
    organization_type_detail: 'University Transportation Research Center',
    website: 'https://tti.tamu.edu',
    location_city: 'College Station',
    location_state: 'TX',
    region: 'South Central',
    notes: 'TTI is one of the largest university-based transportation research agencies. Extensive pedestrian and signal timing research.',
    had_prior_ss4a_grant: 'no',
    has_action_plan: 'no',
    action_plan_type: 'unknown',
    ss4a_stage: 'no_known_activity',
    underserved_community_relevance: 'medium',
    pedestrian_safety_relevance: 'high',
    university_research_strength: 'high',
    grant_partner_fit: 'high',
    strategic_notes: 'TTI could be an incredible research partner. Their signal timing expertise is complementary to WalkPhase.',
    source: 'Research',
    created_at: '2026-03-23T09:00:00Z',
    updated_at: '2026-03-29T15:00:00Z',
  },
  {
    id: 'org-010',
    organization_name: 'Hillsborough County',
    target_category: 'county',
    organization_type_detail: 'County Government — Transportation Division',
    website: 'https://www.hillsboroughcounty.org',
    location_city: 'Tampa',
    location_state: 'FL',
    region: 'Southeast',
    notes: 'Tampa Bay area has high pedestrian fatality rates. County is actively working on safety improvements.',
    had_prior_ss4a_grant: 'no',
    has_action_plan: 'yes',
    action_plan_type: 'vision_zero',
    ss4a_stage: 'planning_demo_candidate',
    underserved_community_relevance: 'high',
    pedestrian_safety_relevance: 'high',
    university_research_strength: 'not_applicable',
    grant_partner_fit: 'high',
    strategic_notes: 'No prior SS4A grant, has Vision Zero plan, high ped fatality area. Excellent new-entrant candidate.',
    source: 'Research',
    created_at: '2026-03-24T08:00:00Z',
    updated_at: '2026-03-30T06:00:00Z',
  },
  {
    id: 'org-011',
    organization_name: 'City of Albuquerque',
    target_category: 'city',
    organization_type_detail: 'Municipal Government — Department of Municipal Development',
    website: 'https://www.cabq.gov',
    location_city: 'Albuquerque',
    location_state: 'NM',
    region: 'Southwest',
    notes: 'Albuquerque consistently ranks among the most dangerous cities for pedestrians. Active Vision Zero effort.',
    had_prior_ss4a_grant: 'yes',
    has_action_plan: 'yes',
    action_plan_type: 'vision_zero',
    ss4a_stage: 'implementation_candidate',
    underserved_community_relevance: 'high',
    pedestrian_safety_relevance: 'high',
    university_research_strength: 'not_applicable',
    grant_partner_fit: 'high',
    strategic_notes: 'Prior grantee moving to implementation. WalkPhase data could strengthen implementation application significantly.',
    source: 'SS4A Award List FY23',
    created_at: '2026-03-25T10:00:00Z',
    updated_at: '2026-03-29T14:00:00Z',
  },
  {
    id: 'org-012',
    organization_name: 'University of Washington',
    target_category: 'university',
    organization_type_detail: 'Department of Civil & Environmental Engineering — Urban Freight Lab',
    website: 'https://depts.washington.edu/trac',
    location_city: 'Seattle',
    location_state: 'WA',
    region: 'Pacific Northwest',
    notes: 'UW TRAC has strong multimodal transportation research. Seattle context provides rich pedestrian data environment.',
    had_prior_ss4a_grant: 'no',
    has_action_plan: 'no',
    action_plan_type: 'unknown',
    ss4a_stage: 'no_known_activity',
    underserved_community_relevance: 'medium',
    pedestrian_safety_relevance: 'medium',
    university_research_strength: 'high',
    grant_partner_fit: 'medium',
    strategic_notes: 'Good research partner but less pedestrian-specific than some others. Could be valuable for methodology validation.',
    source: 'Research',
    created_at: '2026-03-26T09:00:00Z',
    updated_at: '2026-03-28T11:00:00Z',
  },
]

export const SEED_CONTACTS: Contact[] = [
  {
    id: 'con-001',
    first_name: 'Jennifer',
    last_name: 'Dill',
    full_name: 'Jennifer Dill',
    title: 'Director, Transportation Research & Education Center',
    email: 'jdill@pdx.edu',
    phone: '',
    linkedin_url: 'https://linkedin.com/in/jennifer-dill',
    organization_id: 'org-001',
    contact_type: 'professor',
    seniority: 'high',
    relationship_status: 'queued',
    last_contact_date: '',
    next_action_date: '2026-04-01',
    notes: 'Leading researcher in active transportation. Co-directs TREC. Published on pedestrian safety and signal timing.',
    source: 'University website',
    created_at: '2026-03-15T10:30:00Z',
    updated_at: '2026-03-28T14:30:00Z',
  },
  {
    id: 'con-002',
    first_name: 'Marcus',
    last_name: 'Williams',
    full_name: 'Marcus Williams',
    title: 'Transportation Safety Manager',
    email: 'marcus.williams@orlando.gov',
    phone: '(407) 555-0142',
    linkedin_url: '',
    organization_id: 'org-002',
    contact_type: 'program_manager',
    seniority: 'high',
    relationship_status: 'emailed',
    last_contact_date: '2026-03-25',
    next_action_date: '2026-04-02',
    notes: 'Leads pedestrian safety initiatives. Responded positively to initial outreach about signal timing data.',
    source: 'LinkedIn',
    created_at: '2026-03-16T09:30:00Z',
    updated_at: '2026-03-29T11:30:00Z',
  },
  {
    id: 'con-003',
    first_name: 'Sarah',
    last_name: 'Chen',
    full_name: 'Sarah Chen',
    title: 'Senior Research Associate',
    email: 'schen@hsrc.unc.edu',
    phone: '',
    linkedin_url: 'https://linkedin.com/in/sarahchen-hsrc',
    organization_id: 'org-003',
    contact_type: 'researcher',
    seniority: 'medium',
    relationship_status: 'not_contacted',
    last_contact_date: '',
    next_action_date: '2026-04-03',
    notes: 'Published on pedestrian crossing behavior and signal timing. Could be key research collaborator.',
    source: 'Research paper',
    created_at: '2026-03-17T08:30:00Z',
    updated_at: '2026-03-27T16:30:00Z',
  },
  {
    id: 'con-004',
    first_name: 'David',
    last_name: 'Park',
    full_name: 'David Park',
    title: 'Executive Director',
    email: 'dpark@metroplanorlando.org',
    phone: '(407) 555-0198',
    linkedin_url: '',
    organization_id: 'org-004',
    contact_type: 'director',
    seniority: 'high',
    relationship_status: 'replied',
    last_contact_date: '2026-03-27',
    next_action_date: '2026-04-04',
    notes: 'Interested in WalkPhase for regional pedestrian safety assessment. Wants to discuss pilot program.',
    source: 'Conference',
    created_at: '2026-03-18T10:30:00Z',
    updated_at: '2026-03-28T09:30:00Z',
  },
  {
    id: 'con-005',
    first_name: 'Rachel',
    last_name: 'Torres',
    full_name: 'Rachel Torres',
    title: 'Pedestrian Safety Program Manager',
    email: 'rachel.torres@phoenix.gov',
    phone: '(602) 555-0167',
    linkedin_url: 'https://linkedin.com/in/racheltorres-phoenix',
    organization_id: 'org-005',
    contact_type: 'program_manager',
    seniority: 'high',
    relationship_status: 'queued',
    last_contact_date: '',
    next_action_date: '2026-04-01',
    notes: 'Manages Phoenix Vision Zero pedestrian programs. Key decision maker for safety technology adoption.',
    source: 'LinkedIn',
    created_at: '2026-03-19T11:30:00Z',
    updated_at: '2026-03-30T08:30:00Z',
  },
  {
    id: 'con-006',
    first_name: 'Kari',
    last_name: 'Edison-Watkins',
    full_name: 'Kari Edison-Watkins',
    title: 'Associate Professor, Civil Engineering',
    email: 'kwatkins@gatech.edu',
    phone: '',
    linkedin_url: 'https://linkedin.com/in/kari-edison-watkins',
    organization_id: 'org-006',
    contact_type: 'professor',
    seniority: 'high',
    relationship_status: 'not_contacted',
    last_contact_date: '',
    next_action_date: '2026-04-05',
    notes: 'Research focus on pedestrian signal timing and adaptive control. Potential co-PI for research grant.',
    source: 'Research paper',
    created_at: '2026-03-20T09:30:00Z',
    updated_at: '2026-03-29T10:30:00Z',
  },
  {
    id: 'con-007',
    first_name: 'Michael',
    last_name: 'Rivera',
    full_name: 'Michael Rivera',
    title: 'Transportation Planner',
    email: 'mrivera@sa-mpo.org',
    phone: '(210) 555-0134',
    linkedin_url: '',
    organization_id: 'org-007',
    contact_type: 'planner',
    seniority: 'medium',
    relationship_status: 'not_contacted',
    last_contact_date: '',
    next_action_date: '2026-04-06',
    notes: 'Works on regional safety planning. Could champion WalkPhase for SS4A planning grant application.',
    source: 'LinkedIn',
    created_at: '2026-03-21T08:30:00Z',
    updated_at: '2026-03-28T12:30:00Z',
  },
  {
    id: 'con-008',
    first_name: 'Angela',
    last_name: 'Thompson',
    full_name: 'Angela Thompson',
    title: 'Director of Transportation',
    email: 'athompson@detroitmi.gov',
    phone: '(313) 555-0156',
    linkedin_url: 'https://linkedin.com/in/angelathompson-detroit',
    organization_id: 'org-008',
    contact_type: 'director',
    seniority: 'high',
    relationship_status: 'meeting_booked',
    last_contact_date: '2026-03-28',
    next_action_date: '2026-04-07',
    notes: 'Meeting scheduled to discuss WalkPhase pilot in Detroit. Very engaged and interested in equity angle.',
    source: 'Conference',
    created_at: '2026-03-22T10:30:00Z',
    updated_at: '2026-03-30T07:30:00Z',
  },
  {
    id: 'con-009',
    first_name: 'Robert',
    last_name: 'Brydia',
    full_name: 'Robert Brydia',
    title: 'Senior Research Scientist',
    email: 'r-brydia@tti.tamu.edu',
    phone: '',
    linkedin_url: 'https://linkedin.com/in/robert-brydia',
    organization_id: 'org-009',
    contact_type: 'researcher',
    seniority: 'high',
    relationship_status: 'emailed',
    last_contact_date: '2026-03-26',
    next_action_date: '2026-04-03',
    notes: 'Expert in signal timing and pedestrian operations. Sent initial email about WalkPhase research collaboration.',
    source: 'TTI website',
    created_at: '2026-03-23T09:30:00Z',
    updated_at: '2026-03-29T15:30:00Z',
  },
  {
    id: 'con-010',
    first_name: 'Lisa',
    last_name: 'Hernandez',
    full_name: 'Lisa Hernandez',
    title: 'Transportation Safety Engineer',
    email: 'lisa.hernandez@hillsboroughcounty.org',
    phone: '(813) 555-0189',
    linkedin_url: '',
    organization_id: 'org-010',
    contact_type: 'engineer',
    seniority: 'medium',
    relationship_status: 'queued',
    last_contact_date: '',
    next_action_date: '2026-04-02',
    notes: 'Works on signal timing and pedestrian safety improvements. Good technical contact for WalkPhase evaluation.',
    source: 'LinkedIn',
    created_at: '2026-03-24T08:30:00Z',
    updated_at: '2026-03-30T06:30:00Z',
  },
  {
    id: 'con-011',
    first_name: 'Patricia',
    last_name: 'Reyes',
    full_name: 'Patricia Reyes',
    title: 'Vision Zero Program Director',
    email: 'preyes@cabq.gov',
    phone: '(505) 555-0123',
    linkedin_url: 'https://linkedin.com/in/patricia-reyes-abq',
    organization_id: 'org-011',
    contact_type: 'director',
    seniority: 'high',
    relationship_status: 'emailed',
    last_contact_date: '2026-03-24',
    next_action_date: '2026-04-01',
    notes: 'Very interested in pedestrian signal timing data for implementation grant. Follow up on initial conversation.',
    source: 'SS4A conference',
    created_at: '2026-03-25T10:30:00Z',
    updated_at: '2026-03-29T14:30:00Z',
  },
  {
    id: 'con-012',
    first_name: 'James',
    last_name: 'Liu',
    full_name: 'James Liu',
    title: 'Assistant Professor, Transportation Engineering',
    email: 'jliu@uw.edu',
    phone: '',
    linkedin_url: 'https://linkedin.com/in/james-liu-uw',
    organization_id: 'org-012',
    contact_type: 'professor',
    seniority: 'medium',
    relationship_status: 'not_contacted',
    last_contact_date: '',
    next_action_date: '2026-04-08',
    notes: 'Research on multimodal intersection safety. Could be interested in WalkPhase as a data collection tool.',
    source: 'Research paper',
    created_at: '2026-03-26T09:30:00Z',
    updated_at: '2026-03-28T11:30:00Z',
  },
  {
    id: 'con-013',
    first_name: 'Kevin',
    last_name: 'Mills',
    full_name: 'Kevin Mills',
    title: 'SS4A Grant Coordinator',
    email: 'kevin.mills@orlando.gov',
    phone: '(407) 555-0177',
    linkedin_url: '',
    organization_id: 'org-002',
    contact_type: 'program_manager',
    seniority: 'medium',
    relationship_status: 'not_contacted',
    last_contact_date: '',
    next_action_date: '2026-04-05',
    notes: 'Coordinates SS4A grant applications for Orlando. Secondary contact after Marcus Williams.',
    source: 'LinkedIn',
    created_at: '2026-03-28T14:00:00Z',
    updated_at: '2026-03-29T11:00:00Z',
  },
]

export const SEED_ACTIVITIES: OutreachActivity[] = [
  {
    id: 'act-001',
    organization_id: 'org-002',
    contact_id: 'con-002',
    activity_type: 'email',
    activity_date: '2026-03-25',
    summary: 'Initial outreach email to Marcus about WalkPhase pedestrian signal timing data for Orlando\'s SS4A implementation grant.',
    outcome: 'Email sent, awaiting response',
    next_step: 'Follow up in one week if no reply',
  },
  {
    id: 'act-002',
    organization_id: 'org-004',
    contact_id: 'con-004',
    activity_type: 'email',
    activity_date: '2026-03-22',
    summary: 'Sent introduction email about WalkPhase to David Park at MetroPlan Orlando.',
    outcome: 'David replied expressing interest',
    next_step: 'Schedule a 30-minute call to discuss pilot program',
  },
  {
    id: 'act-003',
    organization_id: 'org-004',
    contact_id: 'con-004',
    activity_type: 'linkedin',
    activity_date: '2026-03-27',
    summary: 'Connected on LinkedIn. David shared an article about MPO pedestrian safety priorities.',
    outcome: 'Strengthened relationship',
    next_step: 'Send meeting invite for next week',
  },
  {
    id: 'act-004',
    organization_id: 'org-008',
    contact_id: 'con-008',
    activity_type: 'meeting',
    activity_date: '2026-03-28',
    summary: 'Introductory call with Angela Thompson. Discussed Detroit\'s pedestrian safety challenges and how WalkPhase could support their implementation grant.',
    outcome: 'Very positive. Angela wants to schedule a demo for her team.',
    next_step: 'Send demo proposal and schedule team presentation',
  },
  {
    id: 'act-005',
    organization_id: 'org-009',
    contact_id: 'con-009',
    activity_type: 'email',
    activity_date: '2026-03-26',
    summary: 'Sent email to Robert Brydia about potential research collaboration on pedestrian signal timing validation.',
    outcome: 'Email sent, awaiting response',
    next_step: 'Follow up in one week',
  },
  {
    id: 'act-006',
    organization_id: 'org-011',
    contact_id: 'con-011',
    activity_type: 'email',
    activity_date: '2026-03-24',
    summary: 'Followed up from SS4A conference conversation. Sent WalkPhase overview document.',
    outcome: 'Patricia replied asking about pricing and pilot structure',
    next_step: 'Send pricing proposal and pilot framework',
  },
  {
    id: 'act-007',
    organization_id: 'org-005',
    contact_id: 'con-005',
    activity_type: 'research',
    activity_date: '2026-03-29',
    summary: 'Researched Phoenix Vision Zero plan and pedestrian fatality data. Identified key intersections for WalkPhase pitch.',
    outcome: 'Prepared tailored outreach materials',
    next_step: 'Send personalized email to Rachel Torres',
  },
  {
    id: 'act-008',
    organization_id: 'org-001',
    contact_id: 'con-001',
    activity_type: 'research',
    activity_date: '2026-03-28',
    summary: 'Reviewed Jennifer Dill\'s recent publications on pedestrian safety and signal timing at TREC.',
    outcome: 'Identified two relevant papers to reference in outreach email',
    next_step: 'Draft personalized email referencing her research',
  },
]
